/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_renxl_jniapp_JniUtils */

#ifndef _Included_com_renxl_jniapp_JniUtils
#define _Included_com_renxl_jniapp_JniUtils

#include "../../../../../../Library/Android/sdk/ndk-bundle/sysroot/usr/include/jni.h"

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    getJniString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renxl_jniapp_JniUtils_getJniString
        (JNIEnv *, jclass);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    accessField
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renxl_jniapp_JniUtils_accessField
        (JNIEnv *, jobject);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    accessStaticField
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_renxl_jniapp_JniUtils_accessStaticField
        (JNIEnv *, jclass);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    accessaMethod
 * Signature: ()V
 */
JNIEXPORT jstring JNICALL Java_com_renxl_jniapp_JniUtils_accessMethod
        (JNIEnv *, jobject);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    accessStaticMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renxl_jniapp_JniUtils_accessStaticMethod
        (JNIEnv *, jclass);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    accessParentMethod
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_renxl_jniapp_JniUtils_accessParentMethod
        (JNIEnv *, jobject);

/*
 * Class:     com_renxl_jniapp_JniUtils
 * Method:    getStringArray
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_renxl_jniapp_JniUtils_getStringArray
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
